### ISSUE TITLE
Executing Python scripts without activating venv: difference to that

### ISSUE THREAD

**Issue by novoid** [guludo/venv-run#2]
Hi,

I have to admit, that I'm rather new to the idea of using virtualenv and so far, I do find it extremely annoying of activating environments before I'm able to invoke my scripts.

Therefore, I'm looking for solutions to make this UX better.

On https://magic-wormhole.readthedocs.io/en/latest/welcome.html#installation I found this:

> You can then run `venv/bin/wormhole` without first activating the virtualenv, so e.g. you could make a symlink from `~/bin/wormhole` to `.../path/to/venv/bin/wormhole`, and then plain `wormhole send` will find it on your `$PATH`.

I could not figure out how magic-wormhole is doing this. However: isn't that even easier than using `venv-run`? Can you explain me the advantage of `venv-run`? Do you know how magic-wormhole is doing this?

Thanks!

**Comment by guludo** [comment]
Hi, there.

Thanks for you interest in this.

> I could not figure out how magic-wormhole is doing this. (...) Do you know how magic-wormhole is doing this?

When you install `magic-wormhole` using `pip`, the latter creates the executable file (i.e., `venv/bin/wormwhole` in your example) with the correct shebang, pointing to the correct `python` executable. This can be easily achieved when `setuptools` is used to create your python package.

If you open `venv/bin/wormhole`, you'll probably see the shebang on the first line containing the absolute path to the environment's python binary.

> However: isn't that even easier than using venv-run?

Well, if you intend to use that program constantly, then yes, linking to the executable seems more interesting than using `venv-run`.

> Can you explain me the advantage of venv-run?

Currently, `venv-run` is just useful to save some typing, that's all. For example, let's say you have a project for a web app and have a file `server.py` to start the development server. Considering that you are keeping your projects dependencies in a virtual environment, you would have to:

```bash
cd path/to/my/project
source my-venv/bin/activate # activate the virtual environment
python server.py # Run your server
# when you're done, deactivate the virtual environment in case you wish to continue using this shell session
deactivate
```

With `venv-run`, you'd just need this:

```bash
cd path/to/my/project
venv-run server.py
```

That said, in most cases you'd also be fine with `my-venv/bin/python server.py` as well. However, another nice thing about `venv-run` is that it also adds `venv-bin/bin` to your `PATH` before calling `server.py`, which is useful for cases when your code calls other executable files that are supposed to be installed in the virtual environment as well.

I hope that answers your questions! :slightly_smiling_face:

**Comment by novoid** [comment]
Oh yeah. Thanks for the answer!
